name: easy_stock_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0' # Flutter 3.19 ve sonrası için sdk: '>=3.3.0 <4.0.0' daha uygun olabilir. Senin versiyonun ^3.8.0 demişsin, bu da gayet iyi.

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  mobile_scanner: ^7.0.1 # Son versiyonu kontrol et, örneğin 5.1.2 veya daha güncel olabilir. `flutter pub outdated` ile bakabilirsin.
  provider: ^6.1.2
  uuid: ^4.4.0
  shared_preferences: ^2.2.3
  image_picker: ^1.1.0 # Son versiyonu kontrol et, örneğin 1.0.7 veya daha güncel olabilir.
  flutter_slidable: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0 # veya ^3.0.0, projenin lint tercihine göre. Senin belirttiğin ^5.0.0 da olabilir.

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/nav_icons/
    - assets/fonts/ # Poppins font dosyalarının bulunduğu klasör
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        # İhtiyaç duyarsan diğer Poppins font ağırlıklarını da (Black, Thin vb.) ekleyebilirsin.
        # Font dosyalarının isimlerinin ve yollarının doğru olduğundan emin ol.